### ISSUE TITLE
web interface

### ISSUE THREAD

**Issue by barkeser2002** [MrLetsplay2003/ShittyAuthServer#1]
web interface nothing changed anything skin settings skin URL and add another login information

screenshots:
<img src="https://i.ibb.co/FBL3Qrp/saaaaa.jpg">

**Comment by TheArrayser** [comment]
`do you are have the english?`

**Comment by barkeser2002** [comment]
little bit:/

**Comment by MrLetsplay2003** [comment]
I've just pushed an update which should fix this issue, please try it again in the newest version to see whether it still exists

**Comment by barkeser2002** [comment]
Yeah buttons are working for new update but skin not uploading request error

**Comment by barkeser2002** [comment]
> Yeah buttons are working for new update but skin not uploading request error

my bad cert files error for post to directory for skin file

**Comment by MrLetsplay2003** [comment]
Are there any errors in the browser console or in the webinterface log?

**Comment by barkeser2002** [comment]
skins are thrown nicely
i getting websocket errors in the variables in the panel, probably because i using an apache proxy

**Comment by MrLetsplay2003** [comment]
Okay, I'm going to close this issue since the original problem seems to be fixed.
As for your proxy setup, make sure you've enabled the `proxy_wstunnel` module and add a rule to your VirtualHost like this:
```apache2
ProxyPassMatch ^/(_internal/ws)$  ws://127.0.0.1:WIAPIPORT/$1
```
