### ISSUE TITLE
 I have a problem

### ISSUE THREAD

**Issue by barkeser2002** [MrLetsplay2003/ShittyAuthServer#2]
skins are not capture by minecraft even though i open an extra apache server

**Comment by barkeser2002** [comment]
Again, I'm sorry, I write all the time.

**Comment by barkeser2002** [comment]
![image](https://user-images.githubusercontent.com/45911502/188020249-44c22ba5-4b66-439d-9731-576ce7f37ab4.png)
https://mc.royalnetwork.xyz/

![apache conf](https://user-images.githubusercontent.com/45911502/188020488-c7f1fb5a-2d4e-4d61-b9dc-024dce54abce.png)

**Comment by MrLetsplay2003** [comment]
Are you using the ShittyAuthLauncher to patch the authlib jar or another tool?

**Comment by barkeser2002** [comment]
i use shittyauthlauncher, authlib 
and custom launcher i crated js pached authlib and launcher login links worked launcher very well but not grab skins file

**Comment by MrLetsplay2003** [comment]
Does the client log show any messages about the skin being invalid/there being some verification error? I tried it with the ShittyAuthLauncher (in MC 1.19.2) on your auth server and my custom skin was working fine

**Comment by barkeser2002** [comment]
i using paper 1.18.2 accounts working fine server turned online mode true and offical preminyum account not joining server and shittyauthserver users joining nicely
patch all server this url https://mc.royalnetwork.xyz 
i testing lower new server and new launcher instance now 
server : spigot 1.16.5
launcher shittylauncher 

spigot no error showing

> [23:05:29] [main/INFO]: Environment: authHost='https://mc.royalnetwork.xyz', accountsHost='https://mc.royalnetwork.xyz', sessionHost='https://mc.royalnetwork.xyz', servicesHost='https://mc.royalnetwork.xyz', name='PROD'
> [23:05:30] [main/INFO]: Found new data pack file/bukkit, loading it automatically
> [23:05:33] [main/INFO]: Reloading ResourceManager: Default, bukkit
> [23:05:36] [Worker-Main-2/INFO]: Loaded 7 recipes
> [23:05:29] [main/INFO]: Environment: authHost='https://mc.royalnetwork.xyz', accountsHost='https://mc.royalnetwork.xyz', sessionHost='https://mc.royalnetwork.xyz', servicesHost='https://mc.royalnetwork.xyz', name='PROD'

minecraft launcher not showing error

> [23:24:11] [Render thread/INFO]: Environment: authHost='https://mc.royalnetwork.xyz', accountsHost='https://mc.royalnetwork.xyz', sessionHost='https://mc.royalnetwork.xyz', servicesHost='https://mc.royalnetwork.xyz', name='PROD'
> [23:24:20] [Render thread/INFO]: Setting user: Hector_Tudors
> [23:24:21] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
> [23:24:29] [Render thread/INFO]: Narrator library for x64 successfully loaded
> [23:24:30] [Render thread/INFO]: Reloading ResourceManager: Default
> [23:24:31] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
> [23:25:01] [Render thread/INFO]: OpenAL initialized.
> [23:25:01] [Render thread/INFO]: Sound engine started
> [23:25:03] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
> [23:25:04] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
> [23:25:04] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
> [23:25:04] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
> [23:25:04] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
> [23:25:04] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
> [23:25:04] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
> [23:25:07] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
> [23:25:08] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
> [23:25:08] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
> [23:26:27] [Render thread/INFO]: Connecting to 0.0.0.0, 25565
> [23:26:40] [Render thread/INFO]: Environment: authHost='https://mc.royalnetwork.xyz', accountsHost='https://mc.royalnetwork.xyz', sessionHost='https://mc.royalnetwork.xyz', servicesHost='https://mc.royalnetwork.xyz', name='PROD'
> [23:27:22] [Render thread/INFO]: Connecting to 0.0.0.0, 25565
> [23:27:41] [Render thread/INFO]: Environment: authHost='https://mc.royalnetwork.xyz', accountsHost='https://mc.royalnetwork.xyz', sessionHost='https://mc.royalnetwork.xyz', servicesHost='https://mc.royalnetwork.xyz', name='PROD'
> [23:27:54] [Render thread/INFO]: [CHAT] Hector_Tudors joined the game
> [23:27:56] [Render thread/INFO]: Loaded 0 advancements
> [23:28:01] [Worker-Main-13/ERROR]: Textures payload has been tampered with (non-whitelisted domain)
> [23:28:01] [Worker-Main-13/ERROR]: Textures payload has been tampered with (non-whitelisted domain)
> [23:30:26] [Render thread/INFO]: Stopping!
> Game exited with exit code 0
 thats all logs

**Comment by MrLetsplay2003** [comment]
The log shows:
`[23:28:01] [Worker-Main-13/ERROR]: Textures payload has been tampered with (non-whitelisted domain)`

That's why the client doesn't show the skin. Try repatching the client's authlib jar and make sure the `patch-skins` is `mc.royalnetwork.xyz` (or just `royalnetwork.xyz` should work too).

**Comment by barkeser2002** [comment]
thanks man working nicely, i going entegrate my custom launcher now thx man

**Comment by MrLetsplay2003** [comment]
I'm going to close this now, since the issue appears to be fixed
