### ISSUE TITLE
Client crash because Server sends content length greater 0 in 204 response when using gzip or deflate

### ISSUE THREAD

**Issue by x0rp01s0n** [MrLetsplay2003/ShittyAuthServer#6]
When using gzip compression, the auth server appends a "Content-Length" header with a value of 20 to the "204 No Content Response."
it causes the shittyauthclient to crash.

test curl command:
`curl -X POST -d '{"accessToken":"52345234-b345f-4333-3330-e56fztuihjf","clientToken":"4fghfhsdrf-c9c5-44tr1-brgb-0rg5667dr445dfc"}' 'http://test.test/validate' -v -H "accept-encoding: gzip"`
will retrurn a content length of 20

When requests are made through proxies, the traffic can potentially be compressed using standard HTTP compression methods such as gzip or deflate. However, if the server appends a content-length header to a 204 response, it can cause a client crash.

**Comment by MrLetsplay2003** [comment]
I'll take a look at it, thank you for reporting the issue :+1:

**Comment by MrLetsplay2003** [comment]
This issue should be fixed in the newest version

**Comment by MrLetsplay2003** [comment]
Closing the issue. Feel free to create a new issue if the problem still exists.
