### ISSUE TITLE
Compilation Failure

### ISSUE THREAD

**Issue by Yolomic** [MrLetsplay2003/ShittyAuthServer#7]
System OS Win11
Maven installed+added to path
![image](https://user-images.githubusercontent.com/51210156/221341747-a4542aef-5534-4fa7-9671-e3afa5256ca4.png)
It says that some plugins are missing
any help would be appriciated or a precompiled jar would be ok as well

**Comment by x0rp01s0n** [comment]
did you clone the repo using `git --recursive`? there are sub modules referenced in this repo that are needed

**Comment by MrLetsplay2003** [comment]
This is most likely because the URL of the Maven repository changed recently. I've updated the `pom.xml` which should fix the issue.

**Comment by MrLetsplay2003** [comment]
Closing the issue. Feel free to create a new issue if the problem still exists.
